// user Name
export const USER_SIGNED ="USER_SIGNED";
export const ERORR_SIGNED = 'ERORR_SIGNED';

export const ADD_USER_PROFILE = 'ADD_USER_PROFILE';
export const REMOVE_USER_PROFILE ="REMOVE_USER_PROFILE";



//messages

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_ALL_MESSAGES ='DELETE_ALL_MESSAGES';
export const GET_NEW_MESSAGES ="GET_NEW_MESSAGES"

// single blog message

export const GET_SINGLE_MESSAGE ='GET_SINGLE_MESSAGE';
export const DELETE_SINGLE_MESSAGE ='DELETE_SINGLE_MESSAGE';


// comments

export const GET_COMMENTS ='GET_COMMENTS';
export const GET_NEW_COMMENTS ='GET_NEW_COMMENTS';
export const ADD_COMMENT ='ADD_COMMENT';
export const DELETE_ALL_COMMENTS ='DELETE_ALL_COMMENTS';

//blogs likes
export const ADD_BLOGS_LIKE ='ADD_BLOGS_LIKE';


//profiles
export const GET_SINGLE_USER ='GET_SINGLE_USER';
export const ADD_PROFILE_TRUST ='ADD_PROFILE_TRUST';
export const SEARCH_PROFILES ='SEARCH_PROFILES';
export const REMOVE_PROFILES ='REMOVE_PROFILES';

//gallery
export const GET_GALLERY_LIST ='GET_GALLERY_LIST';
export const GET_NEW_GALLERY_LIST ='GET_NEW_GALLERY_LIST';
export const REMOVE_GALLERY_IMAGE = 'REMOVE_GALLERY_IMAGE'
export const ADD_GALLERY_IMAGE = 'ADD_GALLERY_IMAGE'
export const REMOVE_GALLERY_LIST ='REMOVE_GALLERY_LIST'; 

export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_BLOG_IMAGE = 'SET_BLOG_IMAGE';
export const REMOVE_PREVIEW_BLOG_IMAGE = 'REMOVE_PREVIEW_BLOG_IMAGE';
//SERVERURL

export const SERVERURL = "/"


//rerender
//export const REFRESH ="REFRESH"
export const PROFILE_DATA = "PROFILE_DATA"