// user Name
export const USER_SIGNED ="USER_SIGNED";
export const ERORR_SIGNED = 'ERORR_SIGNED';

export const ADD_USER_PROFILE = 'ADD_USER_PROFILE';
export const REMOVE_USER_PROFILE ="REMOVE_USER_PROFILE";

//messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_ALL_MESSAGES ='DELETE_ALL_MESSAGES';
export const GET_NEW_MESSAGES ="GET_NEW_MESSAGES"

// single blog message
export const GET_SINGLE_MESSAGE ='GET_SINGLE_MESSAGE';
export const DELETE_SINGLE_MESSAGE ='DELETE_SINGLE_MESSAGE';


// comments
export const GET_COMMENTS ='GET_COMMENTS';
export const GET_NEW_COMMENTS ='GET_NEW_COMMENTS';
export const ADD_COMMENT ='ADD_COMMENT';
export const DELETE_ALL_COMMENTS ='DELETE_ALL_COMMENTS';

//blogs likes
export const ADD_BLOGS_LIKE ='ADD_BLOGS_LIKE';


//profiles
export const GET_SINGLE_USER ='GET_SINGLE_USER';
export const REMOVE_SINGLE_USER = 'REMOVE_SINGLE_USER';
export const ADD_PROFILE_TRUST ='ADD_PROFILE_TRUST';
export const SEARCH_PROFILES ='SEARCH_PROFILES';
export const REMOVE_PROFILES ='REMOVE_PROFILES';

//images
export const UPDATE_PREVIEW_BLOG_IMAGE ="UPDATE_PREVIEW_BLOG_IMAGE";
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_BLOG_IMAGE = 'SET_BLOG_IMAGE';
export const REMOVE_PREVIEW_BLOG_IMAGE = 'REMOVE_PREVIEW_BLOG_IMAGE';

//SERVER_BASE_URL
export const SERVER_BASE_URL = ""


//rerender

export const PROFILE_DATA = "PROFILE_DATA"